sonar.projectKey=nirjxr26_Kost
sonar.organization=nirjxr26
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**
sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
